// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-ZA8ErKpEPj-b2NGFA57me6vivK1OPq4',
    appId: '1:137179985539:web:e9d4c6a137f6c05ac34db6',
    messagingSenderId: '137179985539',
    projectId: 'human-touch-35bd0',
    authDomain: 'human-touch-35bd0.firebaseapp.com',
    storageBucket: 'human-touch-35bd0.firebasestorage.app',
    measurementId: 'G-MSJGEGBPR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPT2Tn1XIT1VnhOq1nteNeyMT9XRbcVNo',
    appId: '1:137179985539:android:8191e316f374f1dec34db6',
    messagingSenderId: '137179985539',
    projectId: 'human-touch-35bd0',
    storageBucket: 'human-touch-35bd0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI9bWLGqmOVmm6HaQU1xcVRVvgutgnBDk',
    appId: '1:137179985539:ios:417aab3e406e4a94c34db6',
    messagingSenderId: '137179985539',
    projectId: 'human-touch-35bd0',
    storageBucket: 'human-touch-35bd0.firebasestorage.app',
    iosBundleId: 'com.example.humantouch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI9bWLGqmOVmm6HaQU1xcVRVvgutgnBDk',
    appId: '1:137179985539:ios:417aab3e406e4a94c34db6',
    messagingSenderId: '137179985539',
    projectId: 'human-touch-35bd0',
    storageBucket: 'human-touch-35bd0.firebasestorage.app',
    iosBundleId: 'com.example.humantouch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-ZA8ErKpEPj-b2NGFA57me6vivK1OPq4',
    appId: '1:137179985539:web:eb05bffee243a49cc34db6',
    messagingSenderId: '137179985539',
    projectId: 'human-touch-35bd0',
    authDomain: 'human-touch-35bd0.firebaseapp.com',
    storageBucket: 'human-touch-35bd0.firebasestorage.app',
    measurementId: 'G-WJ6L3WZ3RJ',
  );

}